### ISSUE TITLE
Epic: Basic locker functionality at the file-level

### ISSUE THREAD

**Issue by sfkleach** [CodeHubOrg/TeamLocker#6]
- [X] Create a Locker
- [ ] List the Lockers you can access
- [ ] Upload/Overwrite a file to a Locker
- [ ] Send an invitation to use a Locker you own
- [ ] Download a previously uploaded file
- [ ] Delete a Locker
